### ISSUE TITLE
Mistral 8x7B 32k 是一个预训练模型还是SFT模型？

### ISSUE THREAD

**Issue by Ezra-Yu** [open-compass/MixtralKit#14]
从 https://klu.ai/glossary/mistral-8x7b 上的信息来看。Mistral 8x7B 32k 是一个sft模型。但目前的评测方式是有些数据集使用的预训练的评测方式。

<img width="850" alt="image" src="https://github.com/open-compass/MixtralKit/assets/18586273/a2ce2dfd-4dd0-4a56-b4d2-bb84bf5f5e58">

我有一些困惑：
Mistral 8x7B 32k 是一个预训练模型还是SFT模型？
[网站](https://klu.ai/glossary/mistral-8x7b) 上的信息是否正确？
你们有这个模型的其他信息吗？

**Comment by tonysy** [comment]
Base: https://huggingface.co/mistralai/Mixtral-8x7B-v0.1
Chat: https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1

**Comment by Ezra-Yu** [comment]
Get that, Thanks. 👍
