### ISSUE TITLE
no checkpoint files found in ./ckpts

### ISSUE THREAD

**Issue by plutoda588** [open-compass/MixtralKit#3]
The problem is that no inference has been made to the model to produce a checkpoint? Or do you need something
The steps I take are as follows：
![image](https://github.com/open-compass/MixtralKit/assets/135417137/f77cdc21-aa80-4a9e-98f9-3ddddad383c2)

(mixtralkit) root@fb05uge0jt0fc-0:/T106/model_main/MixtralKit-main/MixtralKit-main# python tools/example.py -m ./ckpts -t ckpts/tokenizer.model --num-gpus 2
Traceback (most recent call last):
  File "/T106/model_main/MixtralKit-main/MixtralKit-main/tools/example.py", line 63, in <module>
    main()
  File "/T106/model_main/MixtralKit-main/MixtralKit-main/tools/example.py", line 42, in main
    generator = Mixtral.build(
  File "/T106/model_main/MixtralKit-main/MixtralKit-main/mixtralkit/mixtral/generation.py", line 76, in build
    assert len(checkpoints) > 0, f"no checkpoint files found in {ckpt_dir}"
AssertionError: no checkpoint files found in ./ckpts

What should I do about it
@tonysy

**Comment by tonysy** [comment]
You need to download the checkpoints mannually.
<img width="293" alt="image" src="https://github.com/open-compass/MixtralKit/assets/7881589/cf4217d1-2821-4972-bfd8-c52e5ce4840a">

**Comment by plutoda588** [comment]
Thanks you
I didn't replace the model path, it should be “ python tools/example.py -m./model -- path-t model -- path/tokenizer.model --num-gpus 2”, right？

**Comment by tonysy** [comment]
> Thanks you I didn't replace the model path, it should be “ python tools/example.py -m./model -- path-t model -- path/tokenizer.model --num-gpus 2”, right？

Yes, you can try it.

**Comment by tonysy** [comment]
Feel free to re-open if needed.
